// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARHWFNQ_I76Ok8oSU7K7uoud6sRc4WkzA',
    appId: '1:387297444955:web:ce6e6d2d754cad0a4d2b7e',
    messagingSenderId: '387297444955',
    projectId: 'zoom-clone-bbcd1',
    authDomain: 'zoom-clone-bbcd1.firebaseapp.com',
    storageBucket: 'zoom-clone-bbcd1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYtv6hSpJZtABHSUzSN0TLy8ZdXVOmfdU',
    appId: '1:387297444955:android:0749bcbc708fa8574d2b7e',
    messagingSenderId: '387297444955',
    projectId: 'zoom-clone-bbcd1',
    storageBucket: 'zoom-clone-bbcd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUF9MGmXZWC_KTbQheGsGE3-TuSQ0Est0',
    appId: '1:387297444955:ios:ba76ff0354b559b24d2b7e',
    messagingSenderId: '387297444955',
    projectId: 'zoom-clone-bbcd1',
    storageBucket: 'zoom-clone-bbcd1.appspot.com',
    iosClientId: '387297444955-lt3lv96nekl6u6eljniemc3dhbkcqvhn.apps.googleusercontent.com',
    iosBundleId: 'com.appsbymuk.zoomClone',
  );
}
